"""volunteer_id to opportunity_id2

Revision ID: 08d5df101179
Revises: e18d86e3e5dd
Create Date: 2025-04-28 16:44:04.890040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08d5df101179'
down_revision = 'e18d86e3e5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_opportunity',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('required_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('job_id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_table('volunteer_opportunity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('base_points', sa.Integer(), nullable=True),
    sa.Column('current_participants', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opportunity_type', sa.Enum('VOLUNTEER', 'JOB', name='opportunitytype'), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.Enum('OPEN', 'CLOSED', 'FILLED', name='opportunitystatus'),
               existing_nullable=True)
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'CLOSED', 'FILLED', name='opportunitystatus'),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)
        batch_op.drop_column('opportunity_type')

    op.drop_table('volunteer_opportunity')
    op.drop_table('job_opportunity')
    # ### end Alembic commands ###
