"""Remove opportunity_day_id from participant_attendance

Revision ID: 14ebb2e47dd8
Revises: 13ac6ae346dc
Create Date: 2025-05-20 06:36:03.880252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14ebb2e47dd8'
down_revision = '13ac6ae346dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_attendance', schema=None) as batch_op:
        batch_op.drop_constraint('participant_attendance_ibfk_1', type_='foreignkey')
        batch_op.drop_column('opportunity_day_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opportunity_day_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('participant_attendance_ibfk_1', 'opportunity_day', ['opportunity_day_id'], ['id'])

    # ### end Alembic commands ###
