"""OPP chats

Revision ID: 41730835667a
Revises: a8f4ede80bc0
Create Date: 2025-05-28 03:27:23.473422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41730835667a'
down_revision = 'a8f4ede80bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_chat')
    # ### end Alembic commands ###
