"""Added bio and address fields to User

Revision ID: 45c2e0c470d1
Revises: 4c9ecac53e9e
Create Date: 2025-04-14 09:50:19.099555

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45c2e0c470d1"
down_revision = "4c9ecac53e9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "registration_date",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column("city", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("village", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(sa.Column("bio", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("profile_picture", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("experience", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("identity_picture", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "identity_verification_status",
                sa.Enum(
                    "PENDING",
                    "APPROVED",
                    "REJECTED",
                    name="verificationstatus",
                ),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("identity_verification_status")
        batch_op.drop_column("identity_picture")
        batch_op.drop_column("experience")
        batch_op.drop_column("profile_picture")
        batch_op.drop_column("bio")
        batch_op.drop_column("village")
        batch_op.drop_column("city")
        batch_op.drop_column("registration_date")

    # ### end Alembic commands ###
