"""Add org_rating to opportunity_participant

Revision ID: 489e3e2c4d02
Revises: 7ecf75db60e2
Create Date: 2025-05-09 16:27:28.764254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489e3e2c4d02'
down_revision = '7ecf75db60e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reported_type', sa.String(length=50), nullable=True),
    sa.Column('reported_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'REJECTED', name='reportstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunity_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_participant', schema=None) as batch_op:
        batch_op.drop_column('org_rating')

    op.drop_table('report')
    # ### end Alembic commands ###
