""" latitude/longitude

Revision ID: 52619ff529bf
Revises: 08d5df101179
Create Date: 2025-04-28 22:58:37.224487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52619ff529bf'
down_revision = '08d5df101179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
